SELECT nombre FROM producto;
SELECT nombre,precio FROM producto;
SELECT * FROM producto;
SELECT nombre as "nombre de producto", precio as "euros", precio*0.98 as "dólares" FROM producto;
SELECT upper(nombre), precio FROM producto;
SELECT lower(nombre), precio FROM producto;
SELECT nombre, upper(left(nombre,2)) FROM fabricante;
SELECT nombre, round(precio,1) FROM producto;
SELECT nombre, truncate(precio,0) FROM producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre, (precio) from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 2 offset 3;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre, precio from producto order by precio desc limit 1 offset 1;
select nombre from producto where codigo_fabricante=2;
select nombre, (precio) from producto where precio <= 120;
select nombre, (precio) from producto where precio >= 400;
select nombre, precio from producto where not(precio >= 400);
select nombre from producto where precio >= 80 and precio <= 300;
select nombre from producto where precio between 60 and 200;
select nombre from producto where precio>200 and codigo_fabricante=6;
select nombre, precio from producto where codigo_fabricante=1 or codigo_fabricante=3 or codigo_fabricante=5;
select nombre, precio from producto where codigo_fabricante in (1,3,5);
select nombre, precio*100 AS "céntimos" from producto;
select nombre from fabricante where nombre like "S%";
select nombre from fabricante where nombre like "%e";
select nombre from fabricante where nombre like "%w%";
select nombre from fabricante where char_length(nombre)=4;
select nombre from producto where nombre like "%Portátil%";
select nombre from producto where nombre like "%Monitor%" and precio<215;
select nombre, precio from producto where precio >= 180 order by precio desc, nombre asc;