select count(*) from producto;
select count(distinct codigo) from fabricante;
select avg(precio) from producto;
select min(precio) from producto;
select max(precio) from producto;
select nombre,precio from producto order by precio asc limit 1;
select nombre,precio from producto order by precio desc limit 1;
select sum(precio) from producto;
select count(*) from producto where codigo_fabricante = 1;
select avg(precio) from producto where codigo_fabricante = 1;
select min(precio) from producto where codigo_fabricante = 1;
select max(precio) from producto where codigo_fabricante = 1;
select sum(precio) from producto where codigo_fabricante = 1;
select max(precio),min(precio),avg(precio),count(codigo) from producto where codigo_fabricante = 6;
select count(codigo) from producto where precio >= 180;
select codigo_fabricante, count(codigo) as "NumProductos" from producto group by codigo_fabricante order by NumProductos desc;
select codigo_fabricante,max(precio),min(precio),avg(precio) from producto group by codigo_fabricante;
select codigo_fabricante,max(precio),min(precio),avg(precio), count(codigo) from producto group by codigo_fabricante having avg(precio) > 200;
select codigo_fabricante, count(codigo) from producto where precio >= 180 group by codigo_fabricante; 
select codigo_fabricante from producto group by codigo_fabricante having count(codigo) >= 2;
select codigo_fabricante from producto group by codigo_fabricante having sum(precio) > 1000;
select codigo_fabricante, sum(precio) from producto where nombre not like "%monitor%" group by codigo_fabricante having sum(precio) >= 300  order by sum(precio) desc;