select concat_ws(' ', nombre, apellido1, apellido2), sexo from persona where tipo like '%alumno%' order by nombre asc;
select id_asignatura, count(id_alumno) from alumno_se_matricula_asignatura group by id_asignatura; 
select p.nombre, d.nombre from persona as p join profesor as pr on p.id = pr.id_profesor join departamento as d on d.id = pr.id_departamento;
select ag.id, ag.nombre, count(am.id_alumno) from persona as p join alumno_se_matricula_asignatura as am on p.id = am.id_alumno join asignatura as ag on ag.id = am.id_asignatura group by ag.id;
select nombre from asignatura as ag left join profesor as pr on ag.id_profesor = pr.id_profesor where ag.id_profesor is null;
select concat_ws('.',upper(left(nombre,1)), upper(left(apellido1,1)), upper(left(apellido2,1))) as Sigles, nif as DNI from persona;
select 2022-(year(avg(fecha_nacimiento))) as Edat_mitja, 2022-(year(min(fecha_nacimiento))) as Major_edat, 2022-(year(max(fecha_nacimiento))) as Menor_edat from persona;
select pe.nombre, pf.id_profesor, pf.id_departamento from persona pe join profesor pf on pf.id_profesor = pe.id;
select concat_ws(' ', p.nombre, p.apellido1, p.apellido2) as Nom, a.nombre as Assignatura from persona p join asignatura a on a.id = p.id where p.tipo != 'profesor' order by nom asc;
select g.nombre as Grau, concat_ws(' ', p.nombre, p.apellido1, p.apellido2) as Nom from grado g right join persona p on p.id = g.id order by Nom asc;
SELECT concat_ws(' ', nombre, apellido1, apellido2) as 'NombreCompleto', ciudad FROM persona WHERE tipo not like 'profesor' ORDER BY NombreCompleto asc;
SELECT tipo, count(nombre) as 'NumerodeAsignaturas' FROM asignatura WHERE tipo not like 'básica' GROUP BY tipo;
SELECT per.nombre as 'Porfesor', d.nombre as 'Departamento' FROM profesor p JOIN departamento d on p.id_departamento=d.id JOIN persona per on per.id=p.id_profesor;
SELECT count(a.nombre) as 'NumerodeAsignaturas', g.nombre as 'Grado' FROM asignatura a JOIN grado g on a.id_grado=g.id GROUP BY g.nombre;
SELECT count(a.nombre) as 'NumerodeAsignaturas', g.nombre as 'Grado' FROM asignatura a right JOIN grado g on a.id_grado=g.id GROUP BY g.nombre;
SELECT nombre, 2022-year(fecha_nacimiento) FROM persona WHERE tipo LIKE 'alumno' ORDER BY nombre asc;
SELECT curso, sum(creditos) FROM asignatura  WHERE id_grado= 4 GROUP BY curso;
SELECT d.nombre FROM departamento d JOIN  profesor p ON d.id=p.id_departamento GROUP BY d.id HAVING count(p.id_profesor)>=2 ORDER BY d.nombre asc;
SELECT d.nombre, count(p.id_profesor) FROM departamento d left JOIN  profesor p ON d.id=p.id_departamento GROUP BY d.id;
SELECT nombre, apellido1, apellido2, tipo FROM persona WHERE year(fecha_nacimiento) = '1977' and tipo = 'profesor' ORDER BY nombre ASC;
SELECT p.nombre, p.apellido1, p.apellido2, a.nombre FROM persona p JOIN alumno_se_matricula_asignatura al ON p.id=al.id_alumno JOIN curso_escolar c ON al.id_curso_escolar=c.id JOIN asignatura a ON a.id=al.id_asignatura WHERE p.tipo not like 'profesor' and c.anyo_inicio = 2014 and c.anyo_fin = 2015 ORDER BY a.nombre ASC;
SELECT count(pf.id_departamento), d.nombre FROM departamento d JOIN profesor pf ON d.id=pf.id_departamento GROUP BY pf.id_departamento ORDER BY d.nombre ASC;
SELECT d.nombre FROM profesor p RIGHT JOIN departamento d ON p.id_departamento=d.id WHERE p.id_profesor is null ORDER BY d.nombre ASC;
select id,nombre from asignatura where id_profesor like 14 order by id asc;
select id_alumno,count(id_alumno) as "NumeroAsignaturas" from alumno_se_matricula_asignatura group by id_alumno order by id_alumno asc;
select  p.nombre, p.nif as DNI, a.nombre from persona p join asignatura a on p.id = a.id;
select distinct(al.id_alumno), concat_ws(" ",p.nombre,p.apellido1,p.apellido2) as "Nombre Estudiante", al.id_curso_escolar  from persona p  join alumno_se_matricula_asignatura al on p.id=al.id_alumno  where tipo like "alumno";
select * from asignatura where nombre like "C%a%";
select tipo,  count(tipo) as Total from persona group by tipo;
select distinct concat( p.nombre, " ", p.apellido1, " ", apellido2) as Alumno  from persona as p join alumno_se_matricula_asignatura as asm on asm.id_alumno = p.id join curso_escolar as c on asm.id_curso_escolar = c.id where c.anyo_inicio = 2014;
select count(id_asignatura) as total, a.nombre as Nombre_asignatura from persona as p join alumno_se_matricula_asignatura as asm on asm.id_alumno = p.id join asignatura as a on a.id = asm.id_asignatura group by (id_asignatura);
select a.nombre from asignatura as a left join profesor as p on a.id = p.id_profesor where a.id_profesor is null;
SELECT nombre from departamento;
SELECT pe.nombre,pr.id_profesor FROM persona pe join profesor pr on pe.id = pr.id_profesor;
SELECT pe.nombre,pr.id_profesor FROM persona pe left join profesor pr on pe.id = pr.id_profesor;
select nombre, creditos, curso from asignatura where creditos < 5;
select concat_ws(" ",per.nombre, per.apellido1, per.apellido2) as "Nombre de profesor", dep.nombre as "departamento" from persona per join profesor prof on per.id=prof.id_profesor join departamento dep on prof.id_departamento=dep.id where per.tipo = "profesor" order by per.nombre asc;
select concat_ws(" ",per.nombre, per.apellido1, per.apellido2) as "Nombre estudiante", gr.nombre as "Grado" from persona per join asignatura a on per.id = a.id join grado gr on a.id_grado=gr.id where per.tipo = "alumno";
select count(nif) as 'nº de DNI' from persona;
select  upper(nombre) from persona as p  where p.tipo="alumno" and sexo="M"; 
SELECT tipo, floor(avg(datediff(utc_date(),fecha_nacimiento)/365)) as "Media de edad" FROM universidad.persona group by tipo;
SELECT a.nombre as "asignatura",p.nombre FROM universidad.alumno_se_matricula_asignatura as alm join asignatura as a on alm.id_asignatura=a.id join persona as p on p.id=alm.id_alumno; 
SELECT a.nombre as "asignatura",count(p.nombre) FROM universidad.alumno_se_matricula_asignatura as alm join asignatura as a on alm.id_asignatura=a.id join persona as p on p.id=alm.id_alumno group by alm.id_asignatura; 
SELECT a.nombre as "asignatura",p.nombre as "profesor" FROM asignatura as a left join persona as p on a.id_profesor=p.id  where a.curso=1 order by asignatura; 
select creditos from asignatura where nombre='Bases de Datos';
select upper(nombre), upper(apellido1), upper (apellido2) from persona;
select count(distinct nombre) as nombrediferente,count(distinct apellido1) as apellido1diferente, count(distinct apellido2) as apellido2diferente from persona;
select concat_ws(" ", p.nombre, p.apellido1, p.apellido2) as profesor, asi.nombre as asignatura from persona p join profesor pf on p.id=pf.id_profesor join asignatura asi on pf.id_profesor= asi.id_profesor order by profesor asc ;
select concat_ws(" ", p.nombre, p.apellido1, p.apellido2) as profesor, count(pf.id_profesor) as numeroasignatura from persona p join profesor pf on p.id=pf.id_profesor join asignatura asi on pf.id_profesor=asi.id_profesor group by pf.id_profesor order by profesor asc ;
select concat_ws(" ", p.nombre, p.apellido1, p.apellido2) as profesor, asi.nombre as asignatura from persona p join profesor pf on p.id=pf.id_profesor left join asignatura asi on pf.id_profesor=asi.id_profesor;
SELECT upper(concat(nombre,' ',apellido1,' ',apellido2)) as NombresApellidos FROM persona;
SELECT CONCAT(nombre,' ',apellido1, ' ',apellido2) AS nombre FROM persona ORDER BY nombre ASC;
SELECT a.nombre, p.id_departamento from asignatura a JOIN profesor p ON a.id_profesor = p.id_profesor;